name: quote_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.1.2
  flutter_bloc: ^8.1.3
  provider: ^6.0.5
  equatable: ^2.0.5
  shimmer: ^3.0.0
  cached_network_image: ^3.2.3
  google_fonts: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
